### ISSUE TITLE
macos cmake config

### ISSUE THREAD

**Issue by AndrewAnnex** [MichaelHillier/surfe#3]
hello, I am interested in trying out surfe on macos, as there didn't seem to be any platform dependence from what I have seen in the codebase. I am pretty novice cmake user, so I could use some tips for configuring cmake to build surfe, ie the cmake gui is not that populated with options in comparison to the screenshot in the repo

**Comment by MichaelHillier** [comment]
If you click on the "Advanced" checkbox in the cmake gui you should see all the options. Hope this helps and sorry for the very late reply. For some reason I am not getting email notifications for the issues and pull requests.

**Comment by AndrewAnnex** [comment]
you should check your notification settings within github, fairly easy to configure,

I am seeing this error but don't have the time at the moment to dig in: 

```
CMake Warning (dev) at /Users/andrew/ClionProjects/surfe/CMakeLists.txt:69 (target_link_libraries):
  Policy CMP0023 is not set: Plain and keyword target_link_libraries
  signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The keyword signature for target_link_libraries has already been used with
  the target "surfepy".  All uses of target_link_libraries with a target
  should be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * /Users/andrew/ClionProjects/surfe/pybind11/tools/pybind11Tools.cmake:179 (target_link_libraries)
   * /Users/andrew/ClionProjects/surfe/pybind11/tools/pybind11Tools.cmake:107 (target_link_libraries)

This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by MichaelHillier** [comment]
That is a warning which you can ignore - it's not an error. I get that as well.

**Comment by AndrewAnnex** [comment]
okay so that got me further but now I am running into linker issues with eigen and when trying to make math_method.cpp (ld: symbol(s) not found for architecture x86_64). The eigen_include_dir is set to version 3.3.7 installed by homebrew contains the following folders and items
 ```Eigen                              signature_of_eigen3_matrix_library unsupported```, The Eigen folder seems to contain a lot of source code and header files, any tips for making sure I have correctly installed/included eigen?

**Comment by AndrewAnnex** [comment]
gah there is some mixing on my system between homebrew clang, apple clang, and gcc at the moment, switching between whatever defaults I have got me past the eigen issue but then openmp couldn't be found despite what the top level cmake lists file has, also I need to figure out how to just have cmake regen the cache each time I run it

**Comment by MichaelHillier** [comment]
Eigen is simply a header library and there is no installation required. When configuring surfe with cmake you will have to point to where your eigen library is located. 
For the openmp issue, I believe if you don't have it, it should still work. Do you have openmp installed? You can try installing by: sudo apt-get install libomp-dev
If you want to regen the cache by clearing it you can go to File->Delete Cache and that will reset everything.

**Comment by AndrewAnnex** [comment]
closing this issue, see new issue I will make
